Code style fixes
pltrm/PHP-Coding-Style-Guide pull request #1
Opened 2021-11-15 09:03 UTC by ildarsaitkulov

2021-11-15 09:06 UTC, ildarsaitkulov commented on README.md
> +    use FirstTrait, SecondTrait, ThirdTrait;
в mpcmf очень часто пишем вот так

2021-11-15 09:08 UTC, alexbilevskiy commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
список аргументов и return type не нужны в php 7

2021-11-15 09:09 UTC, alexbilevskiy commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать свойства класса, с кратким описанием и указанием типа
тип будет не нужен в 7.4

2021-11-15 09:10 UTC, alexbilevskiy commented on README.md
> +- При инициализации массива, каждый элемент массива ДОЛЖЕН быть на новой строке. НЕОБХОДИМО добавлять запятую в конце каждой строки многострочного массива. После последней НЕОБЯЗАТЕЛЬНО
я думаю, что надо оставить что запятая обязательна даже в последнем элементе. Так удобнее и мы чаще пишем так

2021-11-15 09:14 UTC, ildarsaitkulov commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать свойства класса, с кратким описанием и указанием типа
У нас же не 7.4

2021-11-15 10:18 UTC, Armax15 requested changes

2021-11-15 10:18 UTC, armax15 commented on README.md
> +    'Harry Potter and the Cursed Child'
так а че не так с висящей запятой?это же лучше кмк

2021-11-15 10:18 UTC, armax15 commented on README.md
> +    if ($transaction->type() != 'purchase') { // 1
вот я за то чтобы пихать значения в константы

2021-11-15 10:18 UTC, armax15 commented on README.md
> +    protected const DATE_APPROVED = '2012-06-01';
![image](https://user-images.githubusercontent.com/33004296/141761316-a59335ec-ab19-4975-bb4f-1361333a9ba5.png)

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
надо бы еще прописать что метод должен возвращать определнный тип, чтобы избавляться от кучи проверок в вызывающем коде

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
методы которые вызываются через __call/какой-то неведомый транспорт должны быть описаны в аннотации @see  в точке вызова

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
заменить РЕКОМЕНДУЕТСЯ-> ОБЯЗАТЕЛЬНО `Для каждого аргумента метода и функции РЕКОМЕНДУЕТСЯ использовать Type Hinting. `

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
для документации метода РЕКОМЕНДУЕТСЯ/ОБЯЗАТЕЛЬНО использовать array shapes
https://blog.jetbrains.com/ru/phpstorm/2021/08/phpstorm-2021-2-release/#array-shapes

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
нужно реглмаентировать разбиение длинного вызова метода

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
передача callable в аргументах

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
присваивание в ифах/длинные ифы

2021-11-15 10:18 UTC, Armax15 commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
выбор isset/empty

2021-11-15 10:21 UTC, alexbilevskiy commented on README.md
> +    protected const DATE_APPROVED = '2012-06-01';
нет, выравнивание не нужно

2021-11-15 10:24 UTC, alexbilevskiy commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
> нужно реглмаентировать разбиение длинного вызова метода  

предложи

2021-11-15 10:25 UTC, alexbilevskiy commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
> передача callable в аргументах

уточни, что не нравится

2021-11-15 10:27 UTC, alexbilevskiy commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
> РЕКОМЕНДУЕТСЯ/ОБЯЗАТЕЛЬНО использовать array shapes

имхо, deep assoc completion отлично решает этот вопрос. А то так пхпдок будет слишком большой, мы еще докатимся до того что будем обсуждать а нужно ли разбивать на строки и оставлять висящую запятую в описании массива в phpdoc

2021-11-15 11:59 UTC, Armax15 commented
надо бы еще прописать что метод должен возвращать определнный тип, чтобы избавляться от кучи проверок в вызывающем коде
 
методы которые вызываются через __call/какой-то неведомый транспорт должны быть описаны в аннотации @see в точке вызова
 
заменить РЕКОМЕНДУЕТСЯ-> ОБЯЗАТЕЛЬНО Для каждого аргумента метода и функции РЕКОМЕНДУЕТСЯ использовать Type Hinting.
 
нужно реглмаентировать разбиение длинного вызова метода
Предлагаю разбивать так:
$messages = $this->getMessagesFromElastic(
   $elasticClient,
   $indexes,
   $messagesIds,
   function ($message) {
       //important logic
      
       return $message;
   }
);
 
разбивать цепочки вызова по строкам
$cursor = 
    $mapper
        ->storage()
        ->getCollection($this->db,$currentCollection)
        ->aggregate($groupBнHub, ['cursor' => []]);
 
передача callable в аргументах
если тело callable аргумента занимет больше ~3 строк вынести его в отдельную переменную
 
присваивание в ифах/длинные ифы
 
выбор isset/empty

2021-11-15 12:44 UTC, gilberg-vrn commented on README.md
> +- Для конкатенации строк НЕОБХОДИМО использовать фигурные скобки
РЕКОМЕНДУЕТСЯ использовать sprintf ИЛИ использовать двойные кавычки. При указании переменных в двойных кавычках, переменные НЕОБХОДИМО оборачивать в фигурные скобки

2021-11-15 12:44 UTC, gilberg-vrn commented on README.md
> +    protected const DATE_APPROVED = '2012-06-01';
Я за выравнивание в блоках

Плюс, раз уж это наш кодстайл, то я бы зафиксировал и разделение двойными нижними подчеркиваниями, как например, используется в мапперах

2021-11-15 12:44 UTC, gilberg-vrn commented on README.md
> +use Vendor\Package\FirstTrait;
Еще предлагаю, зафиксировать упрощение имен импортируемых классов, т.е 
НЕ ДОПУСКАЕТСЯ использование полных имен классов, все используемые классы ДОЛЖНЫ быть перечислены в разделе импорта

2021-11-15 12:44 UTC, gilberg-vrn commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
> для документации метода РЕКОМЕНДУЕТСЯ/ОБЯЗАТЕЛЬНО использовать array shapes https://blog.jetbrains.com/ru/phpstorm/2021/08/phpstorm-2021-2-release/#array-shapes

Это ж только 8+?

2021-11-15 12:44 UTC, gilberg-vrn commented on README.md
> +- РЕКОМЕНДУЕТСЯ документировать методы класса. Документация ДОЛЖНА содержать краткое описание метода, список принимаемых аргументов, список выбрасываемых исключений и тип возвращаемого значения
> выбор isset/empty

Тут всё очень на контекст завязано

2021-11-15 12:49 UTC, alexbilevskiy commented
> 4\. разбиение длинного вызова метода
> 5\. разбивать цепочки вызова по строкам

Мне **не** нравятся предложенные примеры. Особенно, пример с aggregate. Там 0 полезной инфы в цепочке вызова до `aggregate(`, это читается просто как единое целое, а ты разбиваешь на кучу лишних строк.
Предлагаю 
а) не делать перенос, если строка умещается в лимит (который в этом пр увеличили до 120)
б) дополнить п.6 про вынос анонимок в отдельную переменную и выносить еще и массивы с >1 элемента
тогда длина строки сократится сильно. НО опять же тут есть исключение, например при работе с  тредпулом, где только один аргумент, он callable и везде на много строк

2021-11-15 12:51 UTC, alexbilevskiy commented on README.md
> +- Для конкатенации строк НЕОБХОДИМО использовать фигурные скобки
приоритеты правильно тогда, сначала двойные кавычки, потом  sprintf.

2021-11-15 12:54 UTC, alexbilevskiy commented
>  Так же стоит подумать над изменением состояния внутри метода и передачу ссылок внутрь метода
>     Неправильный пример

по-моему слишком узкий кейс чтобы вообще тут описывать. Мы так делаем только в воркерах, где нужно хранить батчи там это вполне нормально.

2021-11-15 13:05 UTC, alexbilevskiy commented on README.md
> +    protected const DATE_APPROVED = '2012-06-01';
слишком много придется переделывать. Мы сейчас выравнивание не используем нигде. Даже в тех же самых мапперах.

2021-11-15 13:35 UTC, alexbilevskiy commented
1. fluent-сеттеры и геттеры - я считаю, их надо выпилить. Это только провоцирует писать длинные, нечитаемые цепочки вызовов, с которыми потом опять будут споры про переносы. Ну и не пользуемся мы ими и так.
2. в том разделе где написано что надо заменять foreach на array_map и array_filter - можно убрать вообще или сделать допустимым, а не обязательным, потому что опять же мы везде пишем так, ну и вызов array_map это опять отдельный вызов в стек и всё такое.
3. В исходном документе есть пункт про то, что extends и implements пишутся в одну строку - это как минимум нелогично, потому что например трейты требуют писать наоборот  - по одному на строку.Предлагаю в extends и implements сделать аналогично, что делать переносы ДОПУСТИМО

2021-11-16 07:12 UTC, gilberg-vrn commented on README.md
> +    protected const DATE_APPROVED = '2012-06-01';
А, т.е остальное переделывать не придется?
Да и никто не говорит - изменить прямо здесь и сейчас, только для новых файлов и при редактировании старых

2021-11-16 07:13 UTC, gilberg-vrn commented on README.md
> +- Для конкатенации строк НЕОБХОДИМО использовать фигурные скобки
Ну не скажи, тут надо не приоритет, а ситуации, скорее всего

2023-09-11 10:58 UTC, closed without merging